
services:
  backend-dev:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
      target: dev
    container_name: mern-ecommerce-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://host.docker.internal:27017/products
    depends_on:
      - database

  frontend-dev:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
      target: dev
    container_name: mern-ecommerce-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5001
    depends_on:
      - backend-dev

  database:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mern_db:/data/db

volumes:
  mern_db: {}
  node_modules: {}
