#  development state
FROM node:22-alpine3.21 as dev

# working stage
WORKDIR /app

# copy packege.json and packege-lock.json
COPY backend/package*.json ./
RUN npm install

# copy all files
COPY . .


EXPOSE 5000
# start app in development stage
CMD [ "npx", "nodemon", "server.js" ]